[package]
name = "cdio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
libcdio-sys = "0.5.0"
utf16string = "0.2.0"
vfs = "0.9.0"
